# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Casual' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Casual
  pod 'Firebase/Core'
  pod 'FBSDKCoreKit', '~> 4.40.0'
  pod 'FBSDKLoginKit', '~> 4.40.0'
  pod 'FBSDKShareKit', '~> 4.40.0'
  
  target 'Casual-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CasualTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
